export const USER_LOCALSTORAGE_KEY = 'user'
export const ARTICLES_VIEW_LOCALSTORAGE_KEY = 'articlesView'
export const ARTICLE_LIST_ITEM_INDEX_LOCALSTORAGE_KEY = 'articleListItemIndex'
export const ARTICLE_VIEW_ITEM_INDEX_LOCALSTORAGE_KEY = 'articleViewItemIndex'
export const LOCAL_STORAGE_THEME_KEY = 'theme'
