export const USER_LOCALSTORAGE_KEY = 'user'
export const ARTICLE_LIST_ITEM_INDEX_LOCALSTORAGE_KEY = 'articleListItemIndex'
export const ARTICLE_VIEW_ITEM_INDEX_LOCALSTORAGE_KEY = 'articleViewItemIndex'
export const LOCAL_STORAGE_THEME_KEY = 'theme'
export const LOCAL_STORAGE_LAST_DESIGN_KEY = 'last_design'
