#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"




# проверяет все файлы
# npm run lint:ts:fix
# npm run prettier
# проверяет только измененные файлы
npx lint-staged
npm run lint:scss:fix
# npm run test:unit
# npm run test:ui